### ISSUE TITLE
New window incognito state

### ISSUE THREAD

**Issue by agoupinets** [cihanuygun/View-on-Same-Tab#1]
When opening media a new window, it will always open in a non-incognito window even when coming from an incognito tab.
The incognito state can be preserved by adding:
```javascript
browser.windows.create({
  url: [info.srcUrl],
  incognito: tab.incognito
});
```

**Comment by cihanuygun** [comment]
Hey @agoupinets thanks for the issue, this is now fixed and shipped. It will be available for update after Mozilla's approval.
